"""initial migration

Revision ID: 110b25c0c7c
Revises: None
Create Date: 2016-02-28 22:37:14.838813

"""

# revision identifiers, used by Alembic.
revision = '110b25c0c7c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
