"""updates roles and permission

Revision ID: 11a786a71f7
Revises: 11643f1ea77
Create Date: 2016-03-16 03:11:45.010781

"""

# revision identifiers, used by Alembic.
revision = '11a786a71f7'
down_revision = '11643f1ea77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
