"""empty message

Revision ID: 3b17300af9f
Revises: 11a786a71f7
Create Date: 2016-03-16 18:59:30.579476

"""

# revision identifiers, used by Alembic.
revision = '3b17300af9f'
down_revision = '11a786a71f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
