"""added password reset functions to user

Revision ID: 3b290bb9121
Revises: 4144717c1f9
Create Date: 2016-03-12 02:57:36.002224

"""

# revision identifiers, used by Alembic.
revision = '3b290bb9121'
down_revision = '4144717c1f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
