"""empty message

Revision ID: 40973002a9
Revises: 413ee08b641
Create Date: 2016-03-08 23:03:37.722622

"""

# revision identifiers, used by Alembic.
revision = '40973002a9'
down_revision = '413ee08b641'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
