"""empty message

Revision ID: 413ee08b641
Revises: bc116dd687
Create Date: 2016-03-08 20:06:48.528247

"""

# revision identifiers, used by Alembic.
revision = '413ee08b641'
down_revision = 'bc116dd687'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
