"""empty message

Revision ID: 4144717c1f9
Revises: c3122bcfbb
Create Date: 2016-03-12 02:54:11.292783

"""

# revision identifiers, used by Alembic.
revision = '4144717c1f9'
down_revision = 'c3122bcfbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
