"""empty message

Revision ID: 54d15aca3c0
Revises: 110b25c0c7c
Create Date: 2016-02-28 22:42:10.812929

"""

# revision identifiers, used by Alembic.
revision = '54d15aca3c0'
down_revision = '110b25c0c7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
