"""added token generation for user registration

Revision ID: c3122bcfbb
Revises: 40973002a9
Create Date: 2016-03-08 23:07:39.508351

"""

# revision identifiers, used by Alembic.
revision = 'c3122bcfbb'
down_revision = '40973002a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
